//블록체인 연결
console.log('starting...');

web3 = new Web3(new Web3.providers.HttpProvider('HTTP://127.0.0.1:8545')); // 메타마스크 연결

if (web3)
	console.log('connected');
else
	console.log('not connected');

//첫번째 계정 조회
let account;

web3.eth.getAccounts(function (err, accs){
	if(err != null){
		alert('There was an error fetching your accounts.')
		return
	}
	if(accs.length == 0){
		alert("Couldn't get any accounts!")
		return
	}
	account = accs[0];
})

// 여기에 우리가 만든 컨트랙트에 접근하는 방법을 제시한다:
/* abi generated by the compiler */
var abi = [
	{
		"constant": false,
		"inputs": [
			{
				"name": "nftNo",
				"type": "uint256"
			},
			{
				"name": "newOwner",
				"type": "string"
			}
		],
		"name": "ownerUpdate",
		"outputs": [],
		"payable": false,
		"type": "function",
		"stateMutability": "nonpayable"
	},
	{
		"constant": false,
		"inputs": [
			{
				"name": "nftNo",
				"type": "uint256"
			},
			{
				"name": "owner",
				"type": "string"
			}
		],
		"name": "createGrowDiaryNft",
		"outputs": [],
		"payable": false,
		"type": "function",
		"stateMutability": "nonpayable"
	},
	{
		"constant": true,
		"inputs": [
			{
				"name": "nftNo",
				"type": "uint256"
			}
		],
		"name": "ownerSearch",
		"outputs": [
			{
				"name": "",
				"type": "string"
			}
		],
		"payable": false,
		"type": "function",
		"stateMutability": "view"
	}
];

//var GrowDiaryContract = web3.eth.contract(abi)

var contractAddress = "0x5C8178041aA2f761910Ba9D726Fd12228f10E00c"; /* our contract address on Ethereum after deploying */
var GrowDiary = new web3.eth.Contract(abi, contractAddress);//GrowDiaryContract.at(contractAddress)
// `GrowDiary`는 우리 컨트랙트의 public 함수와 이벤트에 접근할 수 있다.

