//블록체인 연결
console.log('starting...');

web3 = new Web3(new Web3.providers.HttpProvider('HTTP://127.0.0.1:8545')); // 메타마스크 연결

if (web3)
	console.log('connected');
else
	console.log('not connected');

//첫번째 계정 조회
let account;

web3.eth.getAccounts(function (err, accs){
	if(err != null){
		alert('There was an error fetching your accounts.')
		return
	}
	if(accs.length == 0){
		alert("Couldn't get any accounts!")
		return
	}
	account = accs[0];
})

// 여기에 우리가 만든 컨트랙트에 접근하는 방법을 제시한다:
/* abi generated by the compiler */
var abi = [
	{
		"constant": false,
		"inputs": [
			{
				"name": "_memEmail",
				"type": "string"
			},
			{
				"name": "_nftNo",
				"type": "uint256"
			}
		],
		"name": "createGrowDiaryNft",
		"outputs": [],
		"payable": false,
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"name": "nft",
		"outputs": [
			{
				"name": "memEmail",
				"type": "string"
			},
			{
				"name": "nftNo",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	}
];

//var GrowDiaryContract = web3.eth.contract(abi)

var contractAddress = "0x17703228683A680eE60D11bdA25D2f7473CD6c74"; /* our contract address on Ethereum after deploying */

var GrowDiary = new web3.eth.Contract(abi, contractAddress);//GrowDiaryContract.at(contractAddress)
// `GrowDiary`는 우리 컨트랙트의 public 함수와 이벤트에 접근할 수 있다.

// 일종의 이벤트 리스너가 텍스트 입력값을 취한다:
$("#createNft").click(function(e) {
	//var name = $("#nameInput").val()
	// 우리 컨트랙트의 `createGrowDiaryNft`함수를 호출한다:
	var memEmail = "bbb@abc.com";
	var nftNo = 1;
	GrowDiary.methods.createGrowDiaryNft(memEmail, nftNo)
	.send({from: account, })
	.then(function(result){console.log(result);})
})

