//블록체인 연결
console.log('starting...');

if (typeof web3 !== 'undefined') {
        // Mist/MetaMask의 프로바이더 사용
        web3 = new Web3(window.web3.currentProvider);
        //alert('web3가 연결되었습니다.');
    } else {
        // 사용자가 Metamask를 설치하지 않은 경우에 대해 처리
        // 사용자들에게 Metamask를 설치하라는 등의 메세지를 보여줄 것
        web3 = new Web3(new Web3.providers.HttpProvider("http://127.0.0.1:8545"));
}

if (web3)
	console.log('connected');
else
	console.log('not connected');

//첫번째 계정 조회
let account ;

// 여기에 우리가 만든 컨트랙트에 접근하는 방법을 제시한다:
/* abi generated by the compiler */
var abi = [
	{
		"constant": false,
		"inputs": [
			{
				"name": "nftNo",
				"type": "uint256"
			},
			{
				"name": "newOwner",
				"type": "string"
			}
		],
		"name": "ownerUpdate",
		"outputs": [],
		"payable": false,
		"type": "function",
		"stateMutability": "nonpayable"
	},
	{
		"constant": false,
		"inputs": [
			{
				"name": "nftNo",
				"type": "uint256"
			},
			{
				"name": "owner",
				"type": "string"
			}
		],
		"name": "createGrowDiaryNft",
		"outputs": [],
		"payable": false,
		"type": "function",
		"stateMutability": "nonpayable"
	},
	{
		"constant": true,
		"inputs": [
			{
				"name": "nftNo",
				"type": "uint256"
			}
		],
		"name": "ownerSearch",
		"outputs": [
			{
				"name": "",
				"type": "string"
			}
		],
		"payable": false,
		"type": "function",
		"stateMutability": "view"
	}
];

//var GrowDiaryContract = web3.eth.contract(abi)

var contractAddress = "0x5d3A7CeC0B3f126F09D4Ab6De49F7A2cEe669E39"; /* our contract address on Ethereum after deploying */
var GrowDiary = new web3.eth.Contract(abi, contractAddress);//GrowDiaryContract.at(contractAddress)
// `GrowDiary`는 우리 컨트랙트의 public 함수와 이벤트에 접근할 수 있다.

// 여기에 우리가 만든 컨트랙트에 접근하는 방법을 제시한다:
/* abi generated by the compiler */
var abi2 = [
	{
		"constant": false,
		"inputs": [
			{
				"name": "_aucnNo",
				"type": "uint256"
			}
		],
		"name": "withdraw",
		"outputs": [
			{
				"name": "",
				"type": "bool"
			}
		],
		"payable": false,
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"constant": false,
		"inputs": [
			{
				"name": "_aucnNo",
				"type": "uint256"
			}
		],
		"name": "auctionEnd",
		"outputs": [],
		"payable": false,
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"constant": false,
		"inputs": [
			{
				"name": "_beneficiary",
				"type": "address"
			},
			{
				"name": "_aucnNo",
				"type": "uint256"
			},
			{
				"name": "highestBidder",
				"type": "address"
			},
			{
				"name": "highestBid",
				"type": "uint256"
			},
			{
				"name": "amount",
				"type": "uint256"
			},
			{
				"name": "ended",
				"type": "bool"
			}
		],
		"name": "NFTAuction",
		"outputs": [],
		"payable": false,
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"constant": false,
		"inputs": [
			{
				"name": "_aucnNo",
				"type": "uint256"
			}
		],
		"name": "bid",
		"outputs": [],
		"payable": true,
		"stateMutability": "payable",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"name": "AuctionMapping",
		"outputs": [
			{
				"name": "beneficiary",
				"type": "address"
			},
			{
				"name": "aucnNo",
				"type": "uint256"
			},
			{
				"name": "highestBidder",
				"type": "address"
			},
			{
				"name": "highestBid",
				"type": "uint256"
			},
			{
				"name": "amount",
				"type": "uint256"
			},
			{
				"name": "ended",
				"type": "bool"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"name": "bidder",
				"type": "address"
			},
			{
				"indexed": false,
				"name": "amount",
				"type": "uint256"
			}
		],
		"name": "HighestBidIncreased",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"name": "winner",
				"type": "address"
			},
			{
				"indexed": false,
				"name": "amount",
				"type": "uint256"
			}
		],
		"name": "AuctionEnded",
		"type": "event"
	}
];

//var NFTAuctionContract = web3.eth.contract(abi2)

var contractAddress2 = "0xE848Fe7124a368FA89BDdE33d75e3C0aAd1D50D9"; /* our contract address on Ethereum after deploying */

var NFTAuction = new web3.eth.Contract(abi2, contractAddress2);//NFTAuctionContract.at(contractAddress)
// `NFTAuction`는 우리 컨트랙트의 public 함수와 이벤트에 접근할 수 있다.
